### ISSUE TITLE
AWS: Deploy our front-end/backends to AWS

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1042]
We keep SCP SAP IT for SAP charging stations and we "move" the rest to AWS.
As we use the same database instance to store the data for SAP and AWS, there is nothing to move except to reconnect charging station to the right backend (EURECOM, ...)
Deploy small sized VMs that can be scaled easily.
Buy the domain for the front-end: e-mobility-group.com.
Resolve inter server communication on AWS: REST Server -> JSon Server

**Comment by jerome-benoit** [comment]
The AWS production landscape is fully functional under https://e-mobility-group.com using a separate empty DB on the production MongoDB cluster. The rest of the setup on AWS production landscape is similar the AWS QA landscape.

**Comment by LucasBrazi06** [comment]
> The AWS production landscape is fully functional under https://e-mobility-group.com using a separate empty DB on the production MongoDB cluster. The rest of the setup on AWS production landscape is similar the AWS QA landscape.

Ok thanks!
Does it work with multiple json servers ?

**Comment by jerome-benoit** [comment]
>     The AWS production landscape is fully functional under
>     https://e-mobility-group.com using a separate empty DB on the
>     production MongoDB cluster. The rest of the setup on AWS
>     production landscape is similar the AWS QA landscape.
>
> Ok thanks!
> Does it work with multiple json servers ?
>
No, one OCCP server for each protocol type as a workaround, just like on 
the AWS QA landscape.
