### ISSUE TITLE
AWS > QA Landscape:  Deploy Front-End and Backends in AWS

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1060]
Create QA Landscape
- [x] Request an account in SLN (cf Olena's email)
- [x] Deploy in AWS our QA front-end/backends + External free MongoDB instance
- [x] Serge to provide credentials of Free Atlas instance (Maybe we can use free instance in new Atlas account)
- [x] Use a free MongoDB instance as QA database

**Comment by jerome-benoit** [comment]
The QA landscape is fully functional and available under https://qa.e-mobility-group.com. 
The DB used is the same as the one on the SCP QA landscape.

**Comment by LucasBrazi06** [comment]
> The QA landscape is fully functional and available under https://qa.e-mobility-group.com.
> The DB used is the same as the one on the SCP QA landscape.

Does the CI is operative ? So we can disrupt the QA on SCP ?

**Comment by jerome-benoit** [comment]
> > The QA landscape is fully functional and available under [qa.e-mobility-group.com](https://qa.e-mobility-group.com).
> > The DB used is the same as the one on the SCP QA landscape.
> 
> Does the CI is operative ? So we can disrupt the QA on SCP ?

The 4 QA pipelines are working. They just need to be switched to the main repositories under your account, as stated in the tasks list above.

**Comment by LucasBrazi06** [comment]
> > > The QA landscape is fully functional and available under [qa.e-mobility-group.com](https://qa.e-mobility-group.com).
> > > The DB used is the same as the one on the SCP QA landscape.
> > 
> > 
> > Does the CI is operative ? So we can disrupt the QA on SCP ?
> 
> The 4 QA pipelines are working. They just need to be switched to the main repositories under your account, as stated in the tasks list above.

Vamos !

**Comment by jerome-benoit** [comment]
I can't do it, only the account owner can do it. Try with the emobility-qa-simulator on codepipeline first to change in the source step the target repo. Not sure it will recreate the webhook properly on GitHub. I'll reconfigure the rest of the pipeline after and remove the webhook on the repo under my account.
All the demo related instances on SCP QA are not on AWS QA. I do not have access to the sources/repos/etc.
