### ISSUE TITLE
Cluster > WS, socket.io server and cluster enablement do not play nicely together

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1097]
Need investigation. 
Wild guess: session and worker affinity.

**Comment by jerome-benoit** [comment]
AWS offers only Apache ActiveMQ as message broker. 
So we will use it to send and receive charging stations OCPP command messages to OCPP server instances.

**Comment by LucasBrazi06** [comment]
> AWS offers only Apache ActiveMQ as message broker.
> So we will use it to send and receive charging stations OCPP command messages to OCPP server instances.

Isn't it not possible to reach the instance right away via a web socket like in SCP ?

**Comment by jerome-benoit** [comment]
> > AWS offers only Apache ActiveMQ as message broker.
> > So we will use it to send and receive charging stations OCPP command messages to OCPP server instances.
> 
> Isn't it not possible to reach the instance right away via a web socket like in SCP ?

Probably with some changes to the chargingstations collection.

**Comment by LucasBrazi06** [comment]
> > Isn't it not possible to reach the instance right away via a web socket like in SCP ?
> 
> Probably with some changes to the chargingstations collection.

Try to implement this solution.
I don't want to introduce a third party tool unless I'm forced to!
Thanks!

**Comment by LucasBrazi06** [comment]
Replaced by LucasBrazi06/ev-dashboard#1750
