### ISSUE TITLE
OCPP Params: Store a new Custom param in the configuration collection in DB

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1293]
New custom param has now a type 'C' in DB to be stored in configurations collection:
Update also the front-end to send this type in the HTTP Request (type='C')

```
{
    "_id" : "SAP-Mougins-02-EBE",
    "configuration" : [ 
        {
            "key" : "MyCustomParam",
            "readonly" : false,
            "custom" : true,
            "value" : "MyCustomValue"
        }, 
        {
            "key" : "RCMBDelta",
            "readonly" : false,
            "value" : "0"
        }, 
        ...
```

**Comment by WillyLellouch** [comment]
I have encountered an issue that might cause problems later on.
The current free input field does not check whether the parameter already exists in the template and so overrides the previous one if saved. This causes then the parameter to get the 'C' type, and while it is easily rectifiable in the back-end, I think it would be a good idea to prevent the override altogether in the front-end.

**Comment by LucasBrazi06** [comment]
> I have encountered an issue that might cause problems later on.
> The current free input field does not check whether the parameter already exists in the template and so overrides the previous one if saved. This causes then the parameter to get the 'C' type, and while it is easily rectifiable in the back-end, I think it would be a good idea to prevent the override altogether in the front-end.

Let's do it the easy way, you can allow any param in the UI and in the backend you don't mark it as Custom if it's already in the configuration.
Ok for you ?

**Comment by WillyLellouch** [comment]
OK

**Comment by LucasBrazi06** [comment]
@WillyLellouch Use a boolean for custom param as discussed.

**Comment by jerome-benoit** [comment]
It works as expected.
