### ISSUE TITLE
Notification > End Of Session: Avoid checking the inactivity to send the End of Charge notification

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1314]
We have a side effect when the user schedule off-peak hours in his car generating inactivities then receiving the notification too early.
Check only the two last consumptions before sending the notification.

**Comment by LucasBrazi06** [comment]
Maybe better to check if there is no consumption in the last 5 mins instead?
To be discussed.
@OliveGerste don't hesitate to schedule me a meeting

**Comment by jerome-benoit** [comment]
QA: not tested but since the merge, does any charge at home users have complained about being notified about a end of his session when he schedule a recharging start hours after having plug his car to the station?

**Comment by LucasBrazi06** [comment]
> QA: not tested but since the merge, does any charge at home users have complained about being notified about a end of his session when he schedule a recharging start hours after having plug his car to the station?

I think they all disabled the notification :-).
I think you can contact Florent P., he'll be willing and happy to test this.

**Comment by jerome-benoit** [comment]
Florent have never been wrongly notified for a end of charge and he's using his car to scheduled the start.

**Comment by LucasBrazi06** [comment]
> Florent have never been wrongly notified for a end of charge and he's using his car to schedule the start.

Perfect so we can close the issue thn.
