### ISSUE TITLE
Asset: Add Settings to connect to the Schneider BMS

### ISSUE THREAD

**Issue by Namachi06** [LucasBrazi06/ev-server#1509]
@LucasBrazi06 commented on [Mon Dec 23 2019](https://github.com/LucasBrazi06/ev-dashboard/issues/1004)

---

@LucasBrazi06 commented on [Thu May 14 2020](https://github.com/LucasBrazi06/ev-dashboard/issues/1004#issuecomment-628824415)

Implement now the backend part to save the settings.
Pay attention to the sensistive data.

**Comment by LucasBrazi06** [comment]
Dups of LucasBrazi06/ev-dashboard#1004
