### ISSUE TITLE
Charger > Charger registration can fail because of registration with a token

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1511]
So far, happens two times. Need to find a reproducibility pattern. 

Workaround: regenerate the registration token and associated links.

**Comment by LucasBrazi06** [comment]
@jerome-benoit any update on this one?

**Comment by jerome-benoit** [comment]
> @jerome-benoit any update on this one?

No. So far, the issue happens just one more time. 

The pb is that when it happens, we can't let the charging station at its current state to do proper debugging: the charging station must be supervised ASAP and we have to make it work immediately.

**Comment by LucasBrazi06** [comment]
I'll provide an extension of the expiration date for the token as asked by Gerald.
If you cannot reproduce, you can close it.

**Comment by jerome-benoit** [comment]
Closed as non reproducible.
