### ISSUE TITLE
Delta > Initial SoC is missing in transaction metervalues 

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1512]
Workaround done.

**Comment by LucasBrazi06** [comment]
Already done & Tested

**Comment by jerome-benoit** [comment]
Gerald said to track the issue within the firmware with Cahors in a mail exchange. But if the workaround is enough, that's fine and I'll close it again ;-)

**Comment by LucasBrazi06** [comment]
> Gerald said to track the issue within the firmware with Cahors in a mail exchange. But if the workaround is enough, that's fine and I'll close it again ;-)

Yes indeed!

**Comment by jerome-benoit** [comment]
Firmware version 3.3.2 deployed. Need to check if the issue is still here.

**Comment by LucasBrazi06** [comment]
The SoC is here now:
![image](https://user-images.githubusercontent.com/25266945/87713202-1f329d80-c7aa-11ea-8919-bfd2021abb0c.png)
