### ISSUE TITLE
Clean API: make the migration task execution method signature as clean as POSIX fopen(), opendir(), etc.

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1617]

**Comment by LucasBrazi06** [comment]
I don't get that one, could you elaborate ?

**Comment by jerome-benoit** [comment]
> I don't get that one, could you elaborate ?

Make the executeTask() a high level API where all the complexity (like locking, tasks type handling, etc.) is pushed inside. Like POSIX high level APIs.

**Comment by LucasBrazi06** [comment]
> Make the executeTask() a high level API where all the complexity (like locking, tasks type handling, etc.) is pushed inside. Like POSIX high level APIs.

I don't see what to improve with MigrationHandler.executeTask() but you can make me a proposal.
