### ISSUE TITLE
Security > Socket.IO: Check the token validity

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1621]

**Comment by jerome-benoit** [comment]
It's already done. The issue, if confirmed, is elsewhere.

**Comment by LucasBrazi06** [comment]
> It's already done. The issue, if confirmed, is elsewhere.

Ok, let me know.

**Comment by fcoutellier** [comment]
@jerome-benoit : Shall we build unit test for this?

**Comment by jerome-benoit** [comment]
> @jerome-benoit : Shall we build unit test for this?

Yes but that's not an easy unit test to write, we have to add a bunch dependencies to ev-server to implement it.
