### ISSUE TITLE
Billing > handle sessions in error

### ISSUE THREAD

**Issue by Ninjeneer** [LucasBrazi06/ev-server#1636]
- In case of if Stripe is not available during a session do not prevent the user to charge

- Session with no billing data should be visible in Session In Error

- Should be possible to create the invoice from session In Error

**Comment by fcoutellier** [comment]
In case of if Stripe is not available during a session do not prevent the user to charge => ok

Session with no billing data should be visible in Session In Error => ok

Should be possible to create the invoice from session In Error => test not possible
