### ISSUE TITLE
Test Static Limitation

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-server#1641]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/9fc3526e-1c72-46d9-83c7-bdabfd3e8827)

**Comment by LucasBrazi06** [comment]
I fixed it and moved it in QA for testing.

**Comment by jerome-benoit** [comment]
Tested and confirmed to work on the Mougins test charger.
