### ISSUE TITLE
Cars - Converters are not converters.... problem

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-server#1643]
Hi Mahdi,

Following the email from Serge I create this task to follow-up on the necessary enhancement to solve it.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7626e301-14da-4e2d-9ef4-36dfdea80c32)

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/078eefb1-3040-4cc3-816e-4dac8d4d0a08)

Check if relevant to remove the converter choice during the car creation for a user and the tab in the visualization of a car in the catalog.

**Comment by fcoutellier** [comment]
Should be fixed with the following PR:
https://github.com/LucasBrazi06/ev-server/pull/1613
https://github.com/LucasBrazi06/ev-dashboard/pull/1752

This issue is to be moved to icebox till Serge confirms if it works as expected.

**Comment by jerome-benoit** [comment]
> Check if relevant to remove the converter choice during the car creation for a user and the tab in the visualization of a car in the catalog.

It's only relevant when there's only one converter for the vehicle. The list choice can stay in grey then. 

++

**Comment by LucasBrazi06** [comment]
> > Check if relevant to remove the converter choice during the car creation for a user and the tab in the visualization of a car in the catalog.
> 
> It's only relevant when there's only one converter for the vehicle. The list choice can stay in grey then.
> 
> ++

I already had a meeting with Mahdi and we'll put a drop down to select the converters (standard, option, alternative in EV-DB).
