### ISSUE TITLE
OCPP<->OCPI: Allow to set Charging Station status

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-server#1650]
Add a function to force the OCPI status of a charging station from the dashboard.
Here are the available statutes:

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/66af1560-80ab-46f4-b238-6434c3042553)

**Comment by jerome-benoit** [comment]
It's from the OCPI specs?
