### ISSUE TITLE
Smart Charging: Pass the arrival timestamp to the Optimizer

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#1671]
Something to think about: Prioritization via timestamps is not happening yet. Currently arrival timestamps on your side are hardcoded I think. Prioritization is more accurate if you pass in the arrival timestamp (e.g. the beginning of the charging process).

**Comment by mariansalceda** [comment]
@fcoutellier theres a problem with the time zones.

**Comment by fcoutellier** [comment]
@LucasBrazi06 There is -2h due to the timezone. From my opinion, UTC should be used here no?
