### ISSUE TITLE
Back-End - Charging Station in error notification form end-user

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-server#1679]
An End-User should be able to push the information that a charging station is in error (charging scenario is failing)

A button on the mobile application should be build in a different issue.

**Comment by jerome-benoit** [comment]
Related issue: https://github.com/LucasBrazi06/ev-server/issues/1650

**Comment by LucasBrazi06** [comment]
> Related issue: #1650

Not related, 1650 is to change a roaming status ;-).

**Comment by LucasBrazi06** [comment]
More related to LucasBrazi06/ev-mobile#31 and Epic LucasBrazi06/ev-dashboard#973

**Comment by jerome-benoit** [comment]
> > Related issue: #1650
> 
> Not related, 1650 is to change a roaming status ;-).

OCPP 1.6 define a list of charging station statuses. Not need to reinvent the wheel for end user issue report to tenant administrators to link it to one of already predefined statuses at the time of the erro.

**Comment by LucasBrazi06** [comment]
> OCPP 1.6 define a list of charging station statuses. Not need to reinvent the wheel for end user issue report to tenant administrators to link it to one of already predefined statuses at the time of the error.

The user just wants to report an issue with the charging station and not necessarily a status error ;-)

**Comment by jerome-benoit** [comment]
> > OCPP 1.6 define a list of charging station statuses. Not need to reinvent the wheel for end user issue report to tenant administrators to link it to one of already predefined statuses at the time of the error.
> 
> The user just wants to report an issue with the charging station and not necessarily a status error ;-)

You add automatically the status at report creation: for example if the status is 'Faulted' since 2 days, the report can be discarded because he tries to use an out of order station.

**Comment by fcoutellier** [comment]
What about if the charging station is simply not usable. Physical damage, connector not accessible, vandalize. Such cases will not be necessarily detected/handled by the OCPP status. However, the charging station will actually not be usable any longer.

**Comment by jerome-benoit** [comment]
> What about if the charging station is simply not usable. Physical damage, connector not accessible, vandalize. Such cases will not be necessarily detected/handled by the OCPP status. However, the charging station will actually not be usable any longer.

You still add automatically all the targeted charging station information snapshot (including the status) to the report. The report granularity is connector -> charging station.

**Comment by fcoutellier** [comment]
To be tested with the UI
