### ISSUE TITLE
Smart Charging: Handle nbr of really used phase

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1710]
Most of the Volkswagen electric vehicles have a current transformer that is 2 phase only.

**Comment by LucasBrazi06** [comment]
I don't get this, could you elaborate ?

**Comment by jerome-benoit** [comment]
> I don't get this, could you elaborate ?

Some electric cars are charging with 2 phases only.

**Comment by LucasBrazi06** [comment]
> > I don't get this, could you elaborate ?
> 
> Some electric cars are charging with 2 phases only.

Ok, it's like using two single phase converters to accelerate the charge (2x8 or 2x16...).

**Comment by jerome-benoit** [comment]
> > > I don't get this, could you elaborate ?
> > 
> > 
> > Some electric cars are charging with 2 phases only.
> 
> Ok, it's like using two single phase converters to accelerate the charge (2x8 or 2x16...).

Probably, I do know how it's done internally and electrically but Volkswagen seems to use 2 phases converters a lot.

**Comment by jerome-benoit** [comment]
At `ChargingSchedulePeriod` creation, its attribute `numberPhases` must be properly filled.

**Comment by LucasBrazi06** [comment]
> At `ChargingSchedulePeriod` creation, its attribute `numberPhases` must be properly filled.

It's not mandatory and I don't think this will bring any added value compared to not providing it.

**Comment by jerome-benoit** [comment]
If you ask the fair share smart charging algorithm to take into account only one phase for one phase car for defining the charging profile, then you have to specify the number of phases used in the profile, otherwise the charging station will not be able to apply the same limit and the overall max power consumption in a zone will not match the real maximum, which not correct. 
If you have a lot of cars using one phase charging at the same time, the gain over the available power for others is significant, especially in power constrained zones which are very commons.

**Comment by fcoutellier** [comment]
@jerome-benoit : Could you please support me with the functional test (real charging)?

**Comment by jerome-benoit** [comment]
> @jerome-benoit : Could you please support me with the functional test (real charging)?

That task either depends on the car electric specification integration in the smart charging or on the possibility to define the number of phases at charging profile creation. 
I think the first is less error prone and require less end-user actions. 

For testing, a single or two phases car is needed (Jaguar or Golf), plug it on a charging station that permit to have per phase metervalues, define a charging profile on the charging station for the next hours, start a transaction attached to the car electric specs, inspect the metervalues sent and the charging profile settings on the charging station.

**Comment by jerome-benoit** [comment]
From last exchange on that topic, I think the last bits to add to properly handle the number of phases in smart charging is to specify it at the charging profile level.

**Comment by LucasBrazi06** [comment]
> From the last exchange on that topic, I think the last bits to add to properly handle the number of phases in smart charging is to specify it at the charging profile level.

Just created an issue to handle this LucasBrazi06/ev-dashboard#1965
