### ISSUE TITLE
Smart Charging - Refactor build car method and handle phases properly 

### ISSUE THREAD

**Issue by OliveGerste** [LucasBrazi06/ev-server#1772]

**Comment by jerome-benoit** [comment]
QA: not tested.

@OliveGerste: what are the validation tests?

**Comment by OliveGerste** [comment]
@jerome-benoit  
I tested via postman, that all the cases for triggering the smart charging still work correctly:
Test cases I handled:
Single phased station (with single phased car, three phased car) (TransactionStart, StatusChange, first meterValue with phases used)
Three phased station (with single phased car, three phased car) (TransactionStart, StatusChange, first meterValue with phases used)
Dc Charger (TransactionStart, StatusChange, first meterValue)

It is a bit cumbersome to do it with postman. 
I think it is also okay to watch the logs for triggering the smart charging, because we have all these cases in production

**Comment by jerome-benoit** [comment]
Ok, so I think that issue can be closed and that you probably need to merge your updated postman collection into the ev-server one. 

Thanks.
