### ISSUE TITLE
Unit tests: Failure at createContext and run because of user session hash change

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1805]
A HTTP error 403 is returned at createContext and during certain test like the settings related one. 
If I comment out that code 

 ```
     if (global.userHashMapIDs.has(`${tenantID}#${userID}`) &&
        global.userHashMapIDs.get(`${tenantID}#${userID}`) !== userHashID) {
        throw new AppError({
          source: Constants.CENTRAL_SERVER,
          errorCode: StatusCodes.FORBIDDEN,
          message: 'User has been updated and will be logged off',
          module: MODULE_NAME,
          method: 'isSessionHashUpdated',
          user: req.user
        });
      }
```

in isSessionHashUpdated method, the error disappears.

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane 
Double check if this is related to the unit test that reassigns the badge from one user to another one.
This is the only scenario that could call this method.

**Comment by LucasBrazi06** [comment]
This property in the config.json must be set to false when running the unit tests:
"monitorDBChange": false,
