### ISSUE TITLE
Use WebSocket features to track charging station connectivity 

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#1918]

**Comment by jerome-benoit** [comment]
TODO: 

+ Check if the HeartBeatInterval or HeartbeatInterval OCPP parameters also need to be applied with the global value in at charger connexion. Or if the Boot Notification is enough.

**Comment by LucasBrazi06** [comment]
Check issue #1945 and do not update the lastSeen if the charger is not present in the DB.

**Comment by jerome-benoit** [comment]
Done.
