### ISSUE TITLE
Onboarding Stefania

### ISSUE THREAD

**Issue by stefania-santimbrean** [LucasBrazi06/ev-server#1921]
Ask for access

- [x] Ask to be added to DL Charge-Angels Dream Team (External)​

- [x] Ask for GitHub access to ev-scp-sap-it and ev-dashboard-new

**Comment by stefania-santimbrean** [comment]
**Trainings to take**

Needed
- [ ] Web Progamming Foundations - 2h
- [ ] TypeScript - 1.5h
- [ ] Swagger - 2h
- [ ] REST API - 1h

Optional
- [ ] npm - 1h
- [ ] Node.js - 0.6h
- [ ] MongoDB - 0.6h
- [ ] Git - 1h

**Comment by stefania-santimbrean** [comment]
**Dev Setup**

- [ ] Database
- [ ] Servers
- [ ] DB Tools
- [ ] DB Cleanup
- [ ] Register Your User
- [ ] Unit Test
- [ ] Postman
- [ ] VS Code IDE

**Comment by LucasBrazi06** [comment]
> * Ask for GitHub access to ev-scp-sap-it and ev-dashboard-new

Done for ev-scp-sap-it repo.
There is no more ev-dashboard-new repo but ev-dashboard and you are already a member of it

**Comment by stefania-santimbrean** [comment]
@LucasBrazi06 thanks! If I look in my Address Book I does not appear that I am a Member of DL Charge-Angels Dream Team (External)​. Could you please add me?

**Comment by LucasBrazi06** [comment]
> thanks! If I look in my Address Book I does not appear that I am a Member of DL Charge-Angels Dream Team (External)​. Could you please add me?

You are in already!
