### ISSUE TITLE
Onboarding Alfons

### ISSUE THREAD

**Issue by Fonsu** [LucasBrazi06/ev-server#1923]
- [x] Ask to be added to DL Charge-Angels Dream Team (External)​
- [x] Ask for GitHub access to `ev-scp-sap-it` and `ev-dashboard`

**Comment by LucasBrazi06** [comment]
Done, let me know by closing the issue

**Comment by Fonsu** [comment]
- [x]  VS Code IDE
- [ ]  Database
- [ ]  Servers
- [ ]  DB Tools
- [ ]  DB Cleanup
- [ ]  Register Your User
- [ ]  Unit Test
- [ ]  Postman

**Comment by Fonsu** [comment]
Trainings

- [x]  SAP Application Router
- [x]  Node.js
- [ ]  MongoDB

**Comment by jerome-benoit** [comment]
You are very close to be assigned your first task via GitHub issue.

**Comment by jerome-benoit** [comment]
@Fonsu: I think you're now ready to start your first development task. 

Could you please confirm? 

Thanks.

**Comment by Fonsu** [comment]
@jerome-benoit yes, I'm ready to start my first task
