### ISSUE TITLE
Disable action button automatically when no row selected

### ISSUE THREAD

**Issue by mahdibenromdhane** [LucasBrazi06/ev-server#2018]
Buttons linked to multi selection should be disabled automatically when no row is selected

**Comment by WillyLellouch** [comment]
Could I have a use case here ? Thanks.

**Comment by mahdibenromdhane** [comment]
> Could I have a use case here ? Thanks.

Button actions of tables with multiselect should be disabled when no row is selected
Example:
Delete button in transactions in error. 
![image](https://user-images.githubusercontent.com/33232018/107648641-dd54d180-6c7c-11eb-9194-65176dd6798a.png)

**Comment by WillyLellouch** [comment]
OK on my end. Button is activated and deactivated as is specified, functionality works as well. 
Closing Issue
