### ISSUE TITLE
Security > IdP protocols support (SAML, OAuth) for authentication

### ISSUE THREAD

**Issue by jerome-benoit** [LucasBrazi06/ev-server#374]
Add IdP support for SAP user authentication in SAP cloud foundry
Its primary usage will be to use SAP IdP service and enable SSO on our tenant.
Next open a new issue for solving the SAP token handling and there will be also multi-tenancy integration.

**Comment by jerome-benoit** [comment]
On SCP, we will kind of offload that feature to an approuter application.

**Comment by LucasBrazi06** [comment]
But we'll have to provide a conf, deploy a service...

**Comment by jerome-benoit** [comment]
> But we'll have to provide a conf, deploy a service...

Using the approuter just for its security features is not really hard to do once we have defined the policies. 

The more difficult part is its usage inside the dashboard and the fact that all client browser requests will go through it.

**Comment by LucasBrazi06** [comment]
Ok, if we manage to get the authentication working with the IdP and get a SAP token that we receive in the backend all the time stored in the front-end via a cookie (I think they use a cookie), we have just to build our token on the fly in express based on the user's email (create the user on the fly if he does not exist) and handle the requests as before with no impact on our side.
What do you think?

**Comment by jerome-benoit** [comment]
> Ok, if we manage to get the authentication working with the IdP and get a SAP token that we receive in the backend all the time stored in the front-end via a cookie (I think they use a cookie), we have just to build our token on the fly in express based on the user's email (create the user on the fly if he does not exist) and handle the requests as before with no impact on our side.
> What do you think?

To begin with, we need to create a repository to host the approuter work I've done and integrate it to dev and QA landscape deployment automation. The repository have to be private.

**Comment by jerome-benoit** [comment]
@captaineaglex : Could you please update that issue status? 

+ The approuter deployment  with IdP SSO protocols proxying is working;
+ [ ] Use MTA for deployment;
+ [ ] SSO integration in the dashboard: 
  + [ ] SCP per dev spaces setup under SCP account
  + [ ] MongoDB dev DB migration on Cloud Atlas

**Comment by captaineaglex** [comment]
- SCP account setup seems ok to carry out the work.
- I am working on the MTA deployment method. There are some client dependent issues. I will solve them and document them for the future.

**Comment by jerome-benoit** [comment]
The way the current deployment works is clear enough? (by having read conf and script in dedicated the repo)

**Comment by captaineaglex** [comment]
Partially clear. I need to go back to them (and review the scripts in detail for sure) once I have working MTA deployment. But, in principle, I think I know how to move forward.

**Comment by captaineaglex** [comment]
I have added SCP config files private repo as a submodule. Pull request has been created.
