### ISSUE TITLE
REST API: Provide RESTFul endpoint + Swagger documentation

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-server#908]
The goal is to provide the list of APIs + Params to Ebee to allow them to test our backend.
They already have a Tenant in SCP and they need to know how to authenticate + access to all the OCPP API and Business API (Session, Chargers, Users...) so the complete REST interface of the backend in the end.
Send me back the documentation (SAP doc format) and Ebee will put a resource on it.

**Comment by LucasBrazi06** [comment]
@jerome-benoit 
I started to work on an Open API Standard yaml document for the TenantService using Swagger (cf. attached the first draft version).
Next we need to build a new API endpoint in parallel (V1.0.0) and replace the current one.
As written, target is TenantService with JSon schema validation in place (JSon schemas not compatible with OAS!) + Swagger UI deployed on our backends SCP/AWS 
Once we have the Tenant Service in place and working, we'll start migrating all the other ones and publish the documentation.
We have also to handle the Auth API endpoint.

(https://app.zenhub.com/files/86094318/c2f61a2a-961d-478f-a6ad-b57387b309cb/download)

**Comment by jerome-benoit** [comment]
> @jerome-benoit
> I started to work on an Open API Standard yaml document for the TenantService using Swagger (cf. attached the first draft version).
> Next we need to build a new API endpoint in parallel (V1.0.0) and replace the current one.
> As written, target is TenantService with JSon schema validation in place (JSon schemas not compatible with OAS!) + Swagger UI deployed on our backends SCP/AWS.

Everything is based on the swagger-ui-express npm package? 

> Once we have the Tenant Service in place and working, we'll start migrating all the other ones and publish the documentation.
> We have also to handle the Auth API endpoint.

The work I've previously done in the branch quoted is lost because of the various git history rewrites. 

> ([app.zenhub.com/files/86094318/c2f61a2a-961d-478f-a6ad-b57387b309cb/download](https://app.zenhub.com/files/86094318/c2f61a2a-961d-478f-a6ad-b57387b309cb/download))

Have you checked that swagger-ui-express package can build the swagger documentation from it?

**Comment by LucasBrazi06** [comment]
> Everything is based on the swagger-ui-express npm package?
I used swagger-editor to generate the service definition file which should be understandable by swagger-ui-express.
We can also deliver it as a dedicated service but I'm ok with using swagger-ui-express delivered with the ev-servers.

> Have you checked that swagger-ui-express package can build the swagger documentation from it?
I haven't checked but it must be compatible with the generated yaml or json standard file by swagger-editor.
